import Foundation

public class SongDatabaseService {
    public static let shared = SongDatabaseService()
    
    public let allSongs: [SongModel]
    
    private init() {
        // Initialize allSongs with the maimai songs data
        var songs: [SongModel] = []
        
        // ongekiAndChunithm songs
songs.append(contentsOf: [
    SongModel(id: "o_1", title: "STARTLINER", category: .ongekiAndChunithm),
    SongModel(id: "o_2", title: "Jump!! Jump!! Jump!!", category: .ongekiAndChunithm),
    SongModel(id: "o_3", title: "Titania", category: .ongekiAndChunithm),
    SongModel(id: "o_4", title: "Change Our MIRAI！", category: .ongekiAndChunithm),
    SongModel(id: "o_5", title: "無敵We are one!!", category: .ongekiAndChunithm),
    SongModel(id: "o_6", title: "ドキドキDREAM!!!", category: .ongekiAndChunithm),
    SongModel(id: "o_7", title: "Still", category: .ongekiAndChunithm),
    SongModel(id: "o_8", title: "Session High⤴", category: .ongekiAndChunithm),
    SongModel(id: "o_9", title: "Agitation！", category: .ongekiAndChunithm),
    SongModel(id: "o_10", title: "管弦楽組曲 第3番 ニ長調「第2曲（G線上のアリア）」BWV.1068-2", category: .ongekiAndChunithm),
    SongModel(id: "o_11", title: "ハート・ビート", category: .ongekiAndChunithm),
    SongModel(id: "o_12", title: "brilliant better", category: .ongekiAndChunithm),
    SongModel(id: "o_13", title: "フォルテシモBELL", category: .ongekiAndChunithm),
    SongModel(id: "o_14", title: "DETARAME ROCK&ROLL THEORY", category: .ongekiAndChunithm),
    SongModel(id: "o_15", title: "私の中の幻想的世界観及びその顕現を想起させたある現実での出来事に関する一考察", category: .ongekiAndChunithm),
    SongModel(id: "o_16", title: "猛進ソリストライフ！", category: .ongekiAndChunithm),
    SongModel(id: "o_17", title: "My Dearest Song", category: .ongekiAndChunithm),
    SongModel(id: "o_18", title: "SPICY SWINGY STYLE", category: .ongekiAndChunithm),
    SongModel(id: "o_19", title: "Bang Babang Bang!!!", category: .ongekiAndChunithm),
    SongModel(id: "o_20", title: "Tic Tac DREAMIN’", category: .ongekiAndChunithm),
    SongModel(id: "o_21", title: "猫祭り", category: .ongekiAndChunithm),
    SongModel(id: "o_22", title: "TRUST", category: .ongekiAndChunithm),
    SongModel(id: "o_23", title: "奏者はただ背中と提琴で語るのみ", category: .ongekiAndChunithm),
    SongModel(id: "o_24", title: "イロトリドリのメロディ", category: .ongekiAndChunithm),
    SongModel(id: "o_25", title: "-OutsideR:RequieM-", category: .ongekiAndChunithm),
    SongModel(id: "o_26", title: "あねぺったん", category: .ongekiAndChunithm),
    SongModel(id: "o_27", title: "なるとなぎのパーフェクトロックンロール教室", category: .ongekiAndChunithm),
    SongModel(id: "o_28", title: "Help me, あーりん！", category: .ongekiAndChunithm),
    SongModel(id: "o_29", title: "Infantoon Fantasy", category: .ongekiAndChunithm),
    SongModel(id: "o_30", title: "幾四音-Ixion-", category: .ongekiAndChunithm),
    SongModel(id: "o_31", title: "Invitation", category: .ongekiAndChunithm),
    SongModel(id: "o_32", title: "その群青が愛しかったようだった", category: .ongekiAndChunithm),
    SongModel(id: "o_33", title: "The wheel to the right", category: .ongekiAndChunithm),
    SongModel(id: "o_34", title: "光線チューニング", category: .ongekiAndChunithm),
    SongModel(id: "o_35", title: "心象蜃気楼", category: .ongekiAndChunithm),
    SongModel(id: "o_36", title: "エンドマークに希望と涙を添えて", category: .ongekiAndChunithm),
    SongModel(id: "o_37", title: "World Vanquisher", category: .ongekiAndChunithm),
    SongModel(id: "o_38", title: "Xevel", category: .ongekiAndChunithm),
    SongModel(id: "o_39", title: "We Gonna Journey", category: .ongekiAndChunithm),
    SongModel(id: "o_40", title: "My First Phone", category: .ongekiAndChunithm),
    SongModel(id: "o_41", title: "怒槌", category: .ongekiAndChunithm),
    SongModel(id: "o_42", title: "TiamaT:F minor", category: .ongekiAndChunithm),
    SongModel(id: "o_43", title: "Kattobi KEIKYU Rider", category: .ongekiAndChunithm),
    SongModel(id: "o_44", title: "玩具狂奏曲 -終焉-", category: .ongekiAndChunithm),
    SongModel(id: "o_45", title: "BOKUTO", category: .ongekiAndChunithm),
    SongModel(id: "o_46", title: "立川浄穢捕物帳", category: .ongekiAndChunithm),
    SongModel(id: "o_47", title: "最強 the サマータイム!!!!!", category: .ongekiAndChunithm),
    SongModel(id: "o_48", title: "UTAKATA", category: .ongekiAndChunithm),
    SongModel(id: "o_49", title: "タテマエと本心の大乱闘", category: .ongekiAndChunithm),
    SongModel(id: "o_50", title: "CHOCOLATE BOMB!!!!", category: .ongekiAndChunithm),
    SongModel(id: "o_51", title: "はちみつアドベンチャー", category: .ongekiAndChunithm),
    SongModel(id: "o_52", title: "popcorn", category: .ongekiAndChunithm),
    SongModel(id: "o_53", title: "宛城、炎上！！", category: .ongekiAndChunithm),
    SongModel(id: "o_54", title: "レーイレーイ", category: .ongekiAndChunithm),
    SongModel(id: "o_55", title: "YURUSHITE", category: .ongekiAndChunithm),
    SongModel(id: "o_56", title: "Climax", category: .ongekiAndChunithm),
    SongModel(id: "o_57", title: "Counselor", category: .ongekiAndChunithm),
    SongModel(id: "o_58", title: "閃鋼のブリューナク", category: .ongekiAndChunithm),
    SongModel(id: "o_59", title: "ポケットからぬりつぶせ！", category: .ongekiAndChunithm),
    SongModel(id: "o_60", title: "トリドリ⇒モリモリ！Lovely fruits☆", category: .ongekiAndChunithm),
    SongModel(id: "o_61", title: "Desperado Waltz", category: .ongekiAndChunithm),
    SongModel(id: "o_62", title: "ハジマリノピアノ", category: .ongekiAndChunithm),
    SongModel(id: "o_63", title: "オーケー？　オーライ！", category: .ongekiAndChunithm),
    SongModel(id: "o_64", title: "サヨナラフリーウェイ", category: .ongekiAndChunithm),
    SongModel(id: "o_65", title: "単一指向性オーバーブルーム", category: .ongekiAndChunithm),
    SongModel(id: "o_66", title: "みなえをチェック！", category: .ongekiAndChunithm),
    SongModel(id: "o_67", title: "Kiss Me Kiss", category: .ongekiAndChunithm),
    SongModel(id: "o_68", title: "BOUNCE & DANCE", category: .ongekiAndChunithm),
    SongModel(id: "o_69", title: "MEGATON BLAST", category: .ongekiAndChunithm),
    SongModel(id: "o_70", title: "Splash Dance!!", category: .ongekiAndChunithm),
    SongModel(id: "o_71", title: "脳天直撃", category: .ongekiAndChunithm),
    SongModel(id: "o_72", title: "宿星審判", category: .ongekiAndChunithm),
    SongModel(id: "o_73", title: "LiftOff", category: .ongekiAndChunithm),
    SongModel(id: "o_74", title: "No Limit RED Force", category: .ongekiAndChunithm),
    SongModel(id: "o_75", title: "Falsum Atlantis.", category: .ongekiAndChunithm),
    SongModel(id: "o_76", title: "ぱくぱく☆がーる", category: .ongekiAndChunithm),
    SongModel(id: "o_77", title: "Limits", category: .ongekiAndChunithm),
    SongModel(id: "o_78", title: "スピカの天秤", category: .ongekiAndChunithm),
    SongModel(id: "o_79", title: "ハードコア・シンドローム", category: .ongekiAndChunithm),
    SongModel(id: "o_80", title: "We Are Us", category: .ongekiAndChunithm),
    SongModel(id: "o_81", title: "テリトリーバトル", category: .ongekiAndChunithm),
    SongModel(id: "o_82", title: "8-EM", category: .ongekiAndChunithm),
    SongModel(id: "o_83", title: "otorii INNOVATED -[i]3-", category: .ongekiAndChunithm),
    SongModel(id: "o_84", title: "Good bye, Merry-Go-Round.", category: .ongekiAndChunithm),
    SongModel(id: "o_85", title: "パズルリボン", category: .ongekiAndChunithm),
    SongModel(id: "o_86", title: "ツクヨミステップ", category: .ongekiAndChunithm),
    SongModel(id: "o_87", title: "コスモポップファンクラブ", category: .ongekiAndChunithm),
    SongModel(id: "o_88", title: "folern", category: .ongekiAndChunithm),
    SongModel(id: "o_89", title: "Transcend Lights", category: .ongekiAndChunithm),
    SongModel(id: "o_90", title: "エータ・ベータ・イータ", category: .ongekiAndChunithm),
    SongModel(id: "o_91", title: "撩乱乙女†無双劇", category: .ongekiAndChunithm),
    SongModel(id: "o_92", title: "See The Light", category: .ongekiAndChunithm),
    SongModel(id: "o_93", title: "蜘蛛の糸", category: .ongekiAndChunithm),
    SongModel(id: "o_94", title: "Catch Me If You Can", category: .ongekiAndChunithm),
    SongModel(id: "o_95", title: "MAGNETAR GIRL", category: .ongekiAndChunithm),
    SongModel(id: "o_96", title: "Don't Fight The Music", category: .ongekiAndChunithm),
    SongModel(id: "o_97", title: "SUPER AMBULANCE", category: .ongekiAndChunithm),
    SongModel(id: "o_98", title: "Ghost Dance", category: .ongekiAndChunithm),
    SongModel(id: "o_99", title: "電光石火", category: .ongekiAndChunithm),
    SongModel(id: "o_100", title: "ピュグマリオンの咒文", category: .ongekiAndChunithm),
    SongModel(id: "o_101", title: "Hainuwele", category: .ongekiAndChunithm),
    SongModel(id: "o_102", title: "Trrricksters!!", category: .ongekiAndChunithm),
    SongModel(id: "o_103", title: "FLUFFY FLASH", category: .ongekiAndChunithm),
    SongModel(id: "o_104", title: "Bad Apple!! feat.nomico ～五十嵐 撫子 Ver.～", category: .ongekiAndChunithm),
    SongModel(id: "o_105", title: "Snow Colored Score", category: .ongekiAndChunithm),
    SongModel(id: "o_106", title: "『ウソテイ』 ～一回戦せりなvsしろなvsなずな～", category: .ongekiAndChunithm),
    SongModel(id: "o_107", title: "GEOMETRIC DANCE", category: .ongekiAndChunithm),
    SongModel(id: "o_108", title: "LAMIA", category: .ongekiAndChunithm),
    SongModel(id: "o_109", title: "Last Kingdom", category: .ongekiAndChunithm),
    SongModel(id: "o_110", title: "STARRED HEART", category: .ongekiAndChunithm),
    SongModel(id: "o_111", title: "Y.Y.Y.計画!!!!", category: .ongekiAndChunithm),
    SongModel(id: "o_112", title: "SQUAD-Phvntom-", category: .ongekiAndChunithm),
    SongModel(id: "o_113", title: "Apollo", category: .ongekiAndChunithm),
    SongModel(id: "o_114", title: "PinqPiq (xovevox Remix)", category: .ongekiAndChunithm),
    SongModel(id: "o_115", title: "WE'RE BACK!!", category: .ongekiAndChunithm),
    SongModel(id: "o_116", title: "インパアフェクシオン・ホワイトガアル", category: .ongekiAndChunithm),
    SongModel(id: "o_117", title: "Ring", category: .ongekiAndChunithm),
])

// touhou songs
songs.append(contentsOf: [
    SongModel(id: "t_1", title: "ソリッド", category: .touhou),
    SongModel(id: "t_2", title: "Bad Apple!! feat.nomico (REDALiCE Remix)", category: .touhou),
    SongModel(id: "t_3", title: "Bad Apple!! feat nomico", category: .touhou),
    SongModel(id: "t_4", title: "CYBER Sparks", category: .touhou),
    SongModel(id: "t_5", title: "Money Money", category: .touhou),
    SongModel(id: "t_6", title: "LOVE EAST", category: .touhou),
    SongModel(id: "t_7", title: "WARNING×WARNING×WARNING", category: .touhou),
    SongModel(id: "t_8", title: "泡沫、哀のまほろば", category: .touhou),
    SongModel(id: "t_9", title: "華鳥風月", category: .touhou),
    SongModel(id: "t_10", title: "色は匂へど散りぬるを", category: .touhou),
    SongModel(id: "t_11", title: "月に叢雲華に風", category: .touhou),
    SongModel(id: "t_12", title: "ネクロファンタジア～Arr.Demetori", category: .touhou),
    SongModel(id: "t_13", title: "Doll Judgment", category: .touhou),
    SongModel(id: "t_14", title: "永遠のメロディ", category: .touhou),
    SongModel(id: "t_15", title: "もうみんなしねばいいのに", category: .touhou),
    SongModel(id: "t_16", title: "宿題が終わらないっ！", category: .touhou),
    SongModel(id: "t_17", title: "東方スイーツ！～鬼畜姉妹と受難メイド～", category: .touhou),
    SongModel(id: "t_18", title: "taboo tears you up", category: .touhou),
    SongModel(id: "t_19", title: "Starlight Vision", category: .touhou),
    SongModel(id: "t_20", title: "幽闇に目醒めしは", category: .touhou),
    SongModel(id: "t_21", title: "物凄い勢いでけーねが物凄いうた", category: .touhou),
    SongModel(id: "t_22", title: "進捗どうですか？", category: .touhou),
    SongModel(id: "t_23", title: "アマノジャクリバース feat. ｙｔｒ", category: .touhou),
    SongModel(id: "t_24", title: "天狗の落とし文 feat. ｙｔｒ", category: .touhou),
    SongModel(id: "t_25", title: "オーディエンスを沸かす程度の能力 feat.タイツォン", category: .touhou),
    SongModel(id: "t_26", title: "Club Ibuki in Break All", category: .touhou),
    SongModel(id: "t_27", title: "チルノのパーフェクトさんすう教室　⑨周年バージョン", category: .touhou),
    SongModel(id: "t_28", title: "チルノのパーフェクトさんすう教室", category: .touhou),
    SongModel(id: "t_29", title: "患部で止まってすぐ溶ける～狂気の優曇華院", category: .touhou),
    SongModel(id: "t_30", title: "究極焼肉レストラン！お燐の地獄亭！", category: .touhou),
    SongModel(id: "t_31", title: "お嫁にしなさいっ！", category: .touhou),
    SongModel(id: "t_32", title: "キャプテン・ムラサのケツアンカー", category: .touhou),
    SongModel(id: "t_33", title: "ひれ伏せ愚民どもっ！", category: .touhou),
    SongModel(id: "t_34", title: "げきオコスティックファイナリアリティぷんぷんマスタースパーク", category: .touhou),
    SongModel(id: "t_35", title: "【東方ニコカラ】秘神マターラ feat.魂音泉【IOSYS】", category: .touhou),
    SongModel(id: "t_36", title: "不思議の国のクリスマス", category: .touhou),
    SongModel(id: "t_37", title: "INFINITE WORLD", category: .touhou),
    SongModel(id: "t_38", title: "Grip & Break down !!", category: .touhou),
    SongModel(id: "t_39", title: "Cosmic Magic Shooter", category: .touhou),
    SongModel(id: "t_40", title: "しゅわスパ大作戦☆", category: .touhou),
    SongModel(id: "t_41", title: "全人類ノ非想天則", category: .touhou),
    SongModel(id: "t_42", title: "Endless, Sleepless Night", category: .touhou),
    SongModel(id: "t_43", title: "White Traveling Girl", category: .touhou),
    SongModel(id: "t_44", title: "No Routine", category: .touhou),
    SongModel(id: "t_45", title: "Scream out! -maimai SONIC WASHER Edit-", category: .touhou),
    SongModel(id: "t_46", title: "隠然", category: .touhou),
    SongModel(id: "t_47", title: "みんなの", category: .touhou),
    SongModel(id: "t_48", title: "幻想のサテライト", category: .touhou),
    SongModel(id: "t_49", title: "待チ人ハ来ズ。", category: .touhou),
    SongModel(id: "t_50", title: "響縁", category: .touhou),
    SongModel(id: "t_51", title: "囲い無き世は一期の月影", category: .touhou),
    SongModel(id: "t_52", title: "儚きもの人間", category: .touhou),
    SongModel(id: "t_53", title: "sweet little sister", category: .touhou),
    SongModel(id: "t_54", title: "ケロ⑨destiny", category: .touhou),
    SongModel(id: "t_55", title: "Phantasm Brigade", category: .touhou),
    SongModel(id: "t_56", title: "蒼空に舞え、墨染の桜", category: .touhou),
    SongModel(id: "t_57", title: "フラグメンツ -T.V. maimai edit-", category: .touhou),
    SongModel(id: "t_58", title: "橙の幻想郷音頭", category: .touhou),
    SongModel(id: "t_59", title: "Starlight Dance Floor", category: .touhou),
    SongModel(id: "t_60", title: "神々の祈り", category: .touhou),
    SongModel(id: "t_61", title: "願いを呼ぶ季節", category: .touhou),
    SongModel(id: "t_62", title: "明星ロケット", category: .touhou),
    SongModel(id: "t_63", title: "緋色のDance", category: .touhou),
    SongModel(id: "t_64", title: "YU-MU", category: .touhou),
    SongModel(id: "t_65", title: "エテルニタス・ルドロジー", category: .touhou),
    SongModel(id: "t_66", title: "エピクロスの虹はもう見えない", category: .touhou),
    SongModel(id: "t_67", title: "四次元跳躍機関", category: .touhou),
    SongModel(id: "t_68", title: "少女幻葬戦慄曲 ～ Necro Fantasia", category: .touhou),
    SongModel(id: "t_69", title: "妖精村の月誕祭 ～Lunate Elf", category: .touhou),
    SongModel(id: "t_70", title: "Jimang Shot", category: .touhou),
    SongModel(id: "t_71", title: "ってゐ！ ～えいえんてゐVer～", category: .touhou),
    SongModel(id: "t_72", title: "東方妖々夢 ～the maximum moving about～", category: .touhou),
    SongModel(id: "t_73", title: "Yet Another ”drizzly rain”", category: .touhou),
    SongModel(id: "t_74", title: "シアワセうさぎ", category: .touhou),
    SongModel(id: "t_75", title: "最速最高シャッターガール", category: .touhou),
    SongModel(id: "t_76", title: "最終鬼畜妹・一部声", category: .touhou),
    SongModel(id: "t_77", title: "ウサテイ", category: .touhou),
    SongModel(id: "t_78", title: "クレイジークレイジーダンサーズ", category: .touhou),
    SongModel(id: "t_79", title: "Help me, ERINNNNNN!!", category: .touhou),
    SongModel(id: "t_80", title: "ナイト・オブ・ナイツ (Cranky Remix)", category: .touhou),
    SongModel(id: "t_81", title: "ナイト・オブ・ナイツ", category: .touhou),
    SongModel(id: "t_82", title: "疾走あんさんぶる", category: .touhou),
    SongModel(id: "t_83", title: "サドマミホリック", category: .touhou),
    SongModel(id: "t_84", title: "最終鬼畜妹フランドール・S", category: .touhou),
    SongModel(id: "t_85", title: "進め！イッスン軍団 -Rebellion of the Dwarfs-", category: .touhou),
    SongModel(id: "t_86", title: "Little \"Sister\" Bitch", category: .touhou),
    SongModel(id: "t_87", title: "Yakumo >>JOINT STRUGGLE (2019 Update)", category: .touhou),
    SongModel(id: "t_88", title: "Imperishable Night 2006 (2016 Refine)", category: .touhou),
    SongModel(id: "t_89", title: "Calamity Fortune", category: .touhou),
    SongModel(id: "t_90", title: "魔理沙は大変なものを盗んでいきました", category: .touhou),
    SongModel(id: "t_91", title: "Drive Your Fire", category: .touhou),
    SongModel(id: "t_92", title: "Oath Act", category: .touhou),
    SongModel(id: "t_93", title: "全力ハッピーライフ", category: .touhou),
    SongModel(id: "t_94", title: "wheel", category: .touhou),
    SongModel(id: "t_95", title: "Witches night", category: .touhou),
    SongModel(id: "t_96", title: "悪戯センセーション", category: .touhou),
    SongModel(id: "t_97", title: "Paranoia", category: .touhou),
    SongModel(id: "t_98", title: "物凄いヴァイブスで魔理沙が物凄いラップ", category: .touhou),
    SongModel(id: "t_99", title: "Sweet Requiem", category: .touhou),
    SongModel(id: "t_100", title: "Dive into The Sky ～initialized～", category: .touhou),
    SongModel(id: "t_101", title: "絡繰りドール", category: .touhou),
    SongModel(id: "t_102", title: "Prismatic", category: .touhou),
    SongModel(id: "t_103", title: "ロストワードクロニカル", category: .touhou),
    SongModel(id: "t_104", title: "今、誰が為のかがり火へ", category: .touhou),
    SongModel(id: "t_105", title: "トランスダンスアナーキー", category: .touhou),
    SongModel(id: "t_106", title: "ハウリング", category: .touhou),
    SongModel(id: "t_107", title: "Melody！", category: .touhou),
    SongModel(id: "t_108", title: "下克上々", category: .touhou),
    SongModel(id: "t_109", title: "紅星ミゼラブル～廃憶編", category: .touhou),
    SongModel(id: "t_110", title: "幻想に咲いた花", category: .touhou),
    SongModel(id: "t_111", title: "マツヨイナイトバグ", category: .touhou),
    SongModel(id: "t_112", title: "Sweets Time", category: .touhou),
    SongModel(id: "t_113", title: "響け！CHIREI MY WAY!", category: .touhou),
    SongModel(id: "t_114", title: "神々が恋した幻想郷", category: .touhou),
    SongModel(id: "t_115", title: "Armageddon", category: .touhou),
    SongModel(id: "t_116", title: "三妖精SAY YA!!!", category: .touhou),
    SongModel(id: "t_117", title: "紅に染まる恋の花", category: .touhou),
    SongModel(id: "t_118", title: "大輪の魂 (feat. AO, 司芭扶)", category: .touhou),
    SongModel(id: "t_119", title: "Spring of Dreams", category: .touhou),
    SongModel(id: "t_120", title: "スカーレット警察のゲットーパトロール24時", category: .touhou),
    SongModel(id: "t_121", title: "銀のめぐり", category: .touhou),
    SongModel(id: "t_122", title: "Destiny Runner", category: .touhou),
    SongModel(id: "t_123", title: "リスペク風神", category: .touhou),
    SongModel(id: "t_124", title: "インターネットサバイバー", category: .touhou),
    SongModel(id: "t_125", title: "つるぺったん", category: .touhou),
    SongModel(id: "t_126", title: "解けないように", category: .touhou),
    SongModel(id: "t_127", title: "HANIPAGANDA", category: .touhou),
])

// popAndAnime songs
songs.append(contentsOf: [
    SongModel(id: "a_1", title: "HOT LIMIT", category: .popAndAnime),
    SongModel(id: "a_2", title: "ネ！コ！", category: .popAndAnime),
    SongModel(id: "a_3", title: "真・ハンサム体操でズンドコホイ", category: .popAndAnime),
    SongModel(id: "a_4", title: "GET!! 夢&DREAM", category: .popAndAnime),
    SongModel(id: "a_5", title: "バラライカ", category: .popAndAnime),
    SongModel(id: "a_6", title: "若い力 -SEGA HARD GIRLS MIX-", category: .popAndAnime),
    SongModel(id: "a_7", title: "セハガガガンバッちゃう！！", category: .popAndAnime),
    SongModel(id: "a_8", title: "ラブリー☆えんじぇる!!", category: .popAndAnime),
    SongModel(id: "a_9", title: "ラブって♡ジュエリー♪えんじぇる☆ブレイク！！", category: .popAndAnime),
    SongModel(id: "a_10", title: "デビル☆アイドル", category: .popAndAnime),
    SongModel(id: "a_11", title: "きらっせ☆ウッド村ファーム", category: .popAndAnime),
    SongModel(id: "a_12", title: "にじよめちゃん体操第一億", category: .popAndAnime),
    SongModel(id: "a_13", title: "Rodeo Machine", category: .popAndAnime),
    SongModel(id: "a_14", title: "true my heart -Lovable mix-", category: .popAndAnime),
    SongModel(id: "a_15", title: "POP STAR", category: .popAndAnime),
    SongModel(id: "a_16", title: "Love or Lies", category: .popAndAnime),
    SongModel(id: "a_17", title: "jelly", category: .popAndAnime),
    SongModel(id: "a_18", title: "美しく燃える森", category: .popAndAnime),
    SongModel(id: "a_19", title: "Love You", category: .popAndAnime),
    SongModel(id: "a_20", title: "come again", category: .popAndAnime),
    SongModel(id: "a_21", title: "Future", category: .popAndAnime),
    SongModel(id: "a_22", title: "ウッーウッーウマウマ(ﾟ∀ﾟ)", category: .popAndAnime),
    SongModel(id: "a_23", title: "NIGHT OF FIRE", category: .popAndAnime),
    SongModel(id: "a_24", title: "YATTA!", category: .popAndAnime),
    SongModel(id: "a_25", title: "fake!fake!", category: .popAndAnime),
    SongModel(id: "a_26", title: "HIMITSUスパーク", category: .popAndAnime),
    SongModel(id: "a_27", title: "ジンギスカン", category: .popAndAnime),
    SongModel(id: "a_28", title: "ポップミュージックは僕のもの", category: .popAndAnime),
    SongModel(id: "a_29", title: "日本の米は世界一", category: .popAndAnime),
    SongModel(id: "a_30", title: "REVIVER オルタンシア・サーガ -蒼の騎士団- オリジナルVer.", category: .popAndAnime),
    SongModel(id: "a_31", title: "前前前世", category: .popAndAnime),
    SongModel(id: "a_32", title: "だから僕は音楽を辞めた", category: .popAndAnime),
    SongModel(id: "a_33", title: "ハム太郎とっとこうた", category: .popAndAnime),
    SongModel(id: "a_34", title: "ウマイネームイズうまみちゃん", category: .popAndAnime),
    SongModel(id: "a_35", title: "Virtual to LIVE", category: .popAndAnime),
    SongModel(id: "a_36", title: "タケモトピアノCMソング", category: .popAndAnime),
    SongModel(id: "a_37", title: "うっせぇわ", category: .popAndAnime),
    SongModel(id: "a_38", title: "夜に駆ける", category: .popAndAnime),
    SongModel(id: "a_39", title: "廻廻奇譚", category: .popAndAnime),
    SongModel(id: "a_40", title: "Shooting Stars", category: .popAndAnime),
    SongModel(id: "a_41", title: "MOON NIGHTのせいにして", category: .popAndAnime),
    SongModel(id: "a_42", title: "ドラゴンエネルギー", category: .popAndAnime),
    SongModel(id: "a_43", title: "veil", category: .popAndAnime),
    SongModel(id: "a_44", title: "泥の分際で私だけの大切を奪おうだなんて", category: .popAndAnime),
    SongModel(id: "a_45", title: "インドア系ならトラックメイカー", category: .popAndAnime),
    SongModel(id: "a_46", title: "YONA YONA DANCE", category: .popAndAnime),
    SongModel(id: "a_47", title: "くらべられっ子", category: .popAndAnime),
    SongModel(id: "a_48", title: "あの世行きのバスに乗ってさらば。", category: .popAndAnime),
    SongModel(id: "a_49", title: "　", category: .popAndAnime),
    SongModel(id: "a_50", title: "吾輩よ猫であれ", category: .popAndAnime),
    SongModel(id: "a_51", title: "Photon Melodies", category: .popAndAnime),
    SongModel(id: "a_52", title: "春を告げる", category: .popAndAnime),
    SongModel(id: "a_53", title: "Princess♂", category: .popAndAnime),
    SongModel(id: "a_54", title: "ヒトガタ", category: .popAndAnime),
    SongModel(id: "a_55", title: "オントロジー", category: .popAndAnime),
    SongModel(id: "a_56", title: "VOLTAGE", category: .popAndAnime),
    SongModel(id: "a_57", title: "剣を抜け！GCCX MAX", category: .popAndAnime),
    SongModel(id: "a_58", title: "ミラクル・ショッピング", category: .popAndAnime),
    SongModel(id: "a_59", title: "おジャ魔女カーニバル!!", category: .popAndAnime),
    SongModel(id: "a_60", title: "踊", category: .popAndAnime),
    SongModel(id: "a_61", title: "残響散歌", category: .popAndAnime),
    SongModel(id: "a_62", title: "アマカミサマ", category: .popAndAnime),
    SongModel(id: "a_63", title: "モンダイナイトリッパー！", category: .popAndAnime),
    SongModel(id: "a_64", title: "Baddest", category: .popAndAnime),
    SongModel(id: "a_65", title: "Blank Paper (Prod. TEMPLIME)", category: .popAndAnime),
    SongModel(id: "a_66", title: "In my world (Prod. KOTONOHOUSE)", category: .popAndAnime),
    SongModel(id: "a_67", title: "阿修羅ちゃん", category: .popAndAnime),
    SongModel(id: "a_68", title: "おとせサンダー", category: .popAndAnime),
    SongModel(id: "a_69", title: "ヒバリ", category: .popAndAnime),
    SongModel(id: "a_70", title: "Hello, Hologram", category: .popAndAnime),
    SongModel(id: "a_71", title: "不機嫌なスリーカード", category: .popAndAnime),
    SongModel(id: "a_72", title: "魂のルフラン", category: .popAndAnime),
    SongModel(id: "a_73", title: "はんぶんこ", category: .popAndAnime),
    SongModel(id: "a_74", title: "あつすぎの歌", category: .popAndAnime),
    SongModel(id: "a_75", title: "さくゆいたいそう", category: .popAndAnime),
    SongModel(id: "a_76", title: "HUMANBORG", category: .popAndAnime),
    SongModel(id: "a_77", title: "ULTRA POWER", category: .popAndAnime),
    SongModel(id: "a_78", title: "Burn My Soul", category: .popAndAnime),
])

// maimai songs
songs.append(contentsOf: [
    SongModel(id: "m_1", title: "Link", category: .maimai),
    SongModel(id: "m_2", title: "ヤミツキ", category: .maimai),
    SongModel(id: "m_3", title: "Secret Sleuth", category: .maimai),
    SongModel(id: "m_4", title: "BLACK ROSE", category: .maimai),
    SongModel(id: "m_5", title: "言ノ葉カルマ", category: .maimai),
    SongModel(id: "m_6", title: "悪戯", category: .maimai),
    SongModel(id: "m_7", title: "言ノ葉遊戯", category: .maimai),
    SongModel(id: "m_8", title: "りばーぶ", category: .maimai),
    SongModel(id: "m_9", title: "洗脳", category: .maimai),
    SongModel(id: "m_10", title: "Barbed Eye", category: .maimai),
    SongModel(id: "m_11", title: "空威張りビヘイビア", category: .maimai),
    SongModel(id: "m_12", title: "分からない", category: .maimai),
    SongModel(id: "m_13", title: "天国と地獄 -言ノ葉リンネ-", category: .maimai),
    SongModel(id: "m_14", title: "相思創愛", category: .maimai),
    SongModel(id: "m_15", title: "咲キ誇レ常世ノ華", category: .maimai),
    SongModel(id: "m_16", title: "Valsqotch", category: .maimai),
    SongModel(id: "m_17", title: "UniTas", category: .maimai),
    SongModel(id: "m_18", title: "モ°ルモ°ル", category: .maimai),
    SongModel(id: "m_19", title: "ここからはじまるプロローグ。", category: .maimai),
    SongModel(id: "m_20", title: "絡めトリック利己ライザー", category: .maimai),
    SongModel(id: "m_21", title: "アポカリプスに反逆の焔を焚べろ", category: .maimai),
    SongModel(id: "m_22", title: "TEmPTaTiON", category: .maimai),
    SongModel(id: "m_23", title: "Now or Never", category: .maimai),
    SongModel(id: "m_24", title: "福宿音屋魂音泉", category: .maimai),
    SongModel(id: "m_25", title: "キリキリ舞Mine", category: .maimai),
    SongModel(id: "m_26", title: "一か罰", category: .maimai),
    SongModel(id: "m_27", title: "♡マイマイマイラブ♡", category: .maimai),
    SongModel(id: "m_28", title: "Blows Up Everything", category: .maimai),
    SongModel(id: "m_29", title: "TwisteD! XD", category: .maimai),
    SongModel(id: "m_30", title: "魔ジョ狩リ", category: .maimai),
    SongModel(id: "m_31", title: "Technicians High", category: .maimai),
    SongModel(id: "m_32", title: "Scarlet Wings", category: .maimai),
    SongModel(id: "m_33", title: "STEREOSCAPE", category: .maimai),
    SongModel(id: "m_34", title: "Crazy Circle", category: .maimai),
    SongModel(id: "m_35", title: "バーチャルダム　ネーション", category: .maimai),
    SongModel(id: "m_36", title: "MAXRAGE", category: .maimai),
    SongModel(id: "m_37", title: "P-qoq", category: .maimai),
    SongModel(id: "m_38", title: "超常マイマイン", category: .maimai),
    SongModel(id: "m_39", title: "でらっくmaimai♪てんてこまい!", category: .maimai),
    SongModel(id: "m_40", title: "SILENT BLUE", category: .maimai),
    SongModel(id: "m_41", title: "雷切-RAIKIRI-", category: .maimai),
    SongModel(id: "m_42", title: "花と、雪と、ドラムンベース。", category: .maimai),
    SongModel(id: "m_43", title: "Ragnarok", category: .maimai),
    SongModel(id: "m_44", title: "larva", category: .maimai),
    SongModel(id: "m_45", title: "keep hopping", category: .maimai),
    SongModel(id: "m_46", title: "FestivaLight", category: .maimai),
    SongModel(id: "m_47", title: "Excalibur ～Revived resolution～", category: .maimai),
    SongModel(id: "m_48", title: "Caliburne ～Story of the Legendary sword～", category: .maimai),
    SongModel(id: "m_49", title: "Justified", category: .maimai),
    SongModel(id: "m_50", title: "Mare Maris", category: .maimai),
    SongModel(id: "m_51", title: "Candy Tall Woman", category: .maimai),
    SongModel(id: "m_52", title: "Kinda Way", category: .maimai),
    SongModel(id: "m_53", title: "Signature", category: .maimai),
    SongModel(id: "m_54", title: "Magical Flavor", category: .maimai),
    SongModel(id: "m_55", title: "デスパレイト", category: .maimai),
    SongModel(id: "m_56", title: "Moon of Noon", category: .maimai),
    SongModel(id: "m_57", title: "Ultranova", category: .maimai),
    SongModel(id: "m_58", title: "曖昧mind", category: .maimai),
    SongModel(id: "m_59", title: "Limit Break", category: .maimai),
    SongModel(id: "m_60", title: "オトヒメモリー☆ウタゲーション", category: .maimai),
    SongModel(id: "m_61", title: "夢花火", category: .maimai),
    SongModel(id: "m_62", title: "いっしそう電☆舞舞神拳！", category: .maimai),
    SongModel(id: "m_63", title: "FFT", category: .maimai),
    SongModel(id: "m_64", title: "Panopticon", category: .maimai),
    SongModel(id: "m_65", title: "四月の雨", category: .maimai),
    SongModel(id: "m_66", title: "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？", category: .maimai),
    SongModel(id: "m_67", title: "Imitation:Loud Lounge", category: .maimai),
    SongModel(id: "m_68", title: "HERA", category: .maimai),
    SongModel(id: "m_69", title: "Selector", category: .maimai),
    SongModel(id: "m_70", title: "Alea jacta est!", category: .maimai),
    SongModel(id: "m_71", title: "AMAZING MIGHTYYYY!!!!", category: .maimai),
    SongModel(id: "m_72", title: "CITRUS MONSTER", category: .maimai),
    SongModel(id: "m_73", title: "Hyper Active", category: .maimai),
    SongModel(id: "m_74", title: "Jumble Rumble", category: .maimai),
    SongModel(id: "m_75", title: "Nitrous Fury", category: .maimai),
    SongModel(id: "m_76", title: "Revive The Rave", category: .maimai),
    SongModel(id: "m_77", title: "GEMINI -M-", category: .maimai),
    SongModel(id: "m_78", title: "スリップフリップ", category: .maimai),
    SongModel(id: "m_79", title: "天火明命", category: .maimai),
    SongModel(id: "m_80", title: "7thSense", category: .maimai),
    SongModel(id: "m_81", title: "PANDORA PARADOXXX", category: .maimai),
    SongModel(id: "m_82", title: "Lividi", category: .maimai),
    SongModel(id: "m_83", title: "Axeria", category: .maimai),
    SongModel(id: "m_84", title: "the EmpErroR", category: .maimai),
    SongModel(id: "m_85", title: "ガラテアの螺旋", category: .maimai),
    SongModel(id: "m_86", title: "QZKago Requiem", category: .maimai),
    SongModel(id: "m_87", title: "Our Wrenally", category: .maimai),
    SongModel(id: "m_88", title: "Contrapasso -paradiso-", category: .maimai),
    SongModel(id: "m_89", title: "Oshama Scramble!", category: .maimai),
    SongModel(id: "m_90", title: "Garakuta Doll Play", category: .maimai),
    SongModel(id: "m_91", title: "Blew Moon", category: .maimai),
    SongModel(id: "m_92", title: "We Gonna Party", category: .maimai),
    SongModel(id: "m_93", title: "MYTHOS", category: .maimai),
    SongModel(id: "m_94", title: "Life Feels Good", category: .maimai),
    SongModel(id: "m_95", title: "Glorious Crown", category: .maimai),
    SongModel(id: "m_96", title: "Aiolos", category: .maimai),
    SongModel(id: "m_97", title: "LANCE", category: .maimai),
    SongModel(id: "m_98", title: "Dragoon", category: .maimai),
    SongModel(id: "m_99", title: "Death Scythe", category: .maimai),
    SongModel(id: "m_100", title: "LUCIA", category: .maimai),
    SongModel(id: "m_101", title: "D✪N’T ST✪P R✪CKIN’", category: .maimai),
    SongModel(id: "m_102", title: "oboro", category: .maimai),
    SongModel(id: "m_103", title: "CYCLES", category: .maimai),
    SongModel(id: "m_104", title: "Lionheart", category: .maimai),
    SongModel(id: "m_105", title: "Heartbeats", category: .maimai),
    SongModel(id: "m_106", title: "Acceleration", category: .maimai),
    SongModel(id: "m_107", title: "End of Twilight", category: .maimai),
    SongModel(id: "m_108", title: "JUMPIN' JUMPIN'", category: .maimai),
    SongModel(id: "m_109", title: "L'épilogue", category: .maimai),
    SongModel(id: "m_110", title: "FEEL ALIVE", category: .maimai),
    SongModel(id: "m_111", title: "FEEL the BEATS", category: .maimai),
    SongModel(id: "m_112", title: "BREAK YOU!!", category: .maimai),
    SongModel(id: "m_113", title: "KING is BACK!!", category: .maimai),
    SongModel(id: "m_114", title: "Streak", category: .maimai),
    SongModel(id: "m_115", title: "Spin me harder", category: .maimai),
    SongModel(id: "m_116", title: "Turn around", category: .maimai),
    SongModel(id: "m_117", title: "SPILL OVER COLORS", category: .maimai),
    SongModel(id: "m_118", title: "Schwarzschild", category: .maimai),
    SongModel(id: "m_119", title: "Black Out", category: .maimai),
    SongModel(id: "m_120", title: "Fragrance", category: .maimai),
    SongModel(id: "m_121", title: "Nerverakes", category: .maimai),
    SongModel(id: "m_122", title: "Sprintrances", category: .maimai),
    SongModel(id: "m_123", title: "air's gravity", category: .maimai),
    SongModel(id: "m_124", title: "Night Fly", category: .maimai),
    SongModel(id: "m_125", title: "Feel My Fire", category: .maimai),
    SongModel(id: "m_126", title: "Starlight Disco", category: .maimai),
    SongModel(id: "m_127", title: "ENJOY POLIS", category: .maimai),
    SongModel(id: "m_128", title: "記憶、記録", category: .maimai),
    SongModel(id: "m_129", title: "connecting with you", category: .maimai),
    SongModel(id: "m_130", title: "アージェントシンメトリー", category: .maimai),
    SongModel(id: "m_131", title: "Dreampainter", category: .maimai),
    SongModel(id: "m_132", title: "Monochrome Rainbow", category: .maimai),
    SongModel(id: "m_133", title: "Beat of getting entangled", category: .maimai),
    SongModel(id: "m_134", title: "MIRROR of MAGIC", category: .maimai),
    SongModel(id: "m_135", title: "Cosmic Train", category: .maimai),
    SongModel(id: "m_136", title: "Believe the Rainbow", category: .maimai),
    SongModel(id: "m_137", title: "高気圧ねこロック", category: .maimai),
    SongModel(id: "m_138", title: "Prophesy One", category: .maimai),
    SongModel(id: "m_139", title: "BETTER CHOICE", category: .maimai),
    SongModel(id: "m_140", title: "Get Happy", category: .maimai),
    SongModel(id: "m_141", title: "System “Z”", category: .maimai),
    SongModel(id: "m_142", title: "ユビキリ", category: .maimai),
    SongModel(id: "m_143", title: "火炎地獄", category: .maimai),
    SongModel(id: "m_144", title: "Danza zandA", category: .maimai),
    SongModel(id: "m_145", title: "planet dancer", category: .maimai),
    SongModel(id: "m_146", title: "ナミダと流星", category: .maimai),
    SongModel(id: "m_147", title: "ピーマンたべたら", category: .maimai),
    SongModel(id: "m_148", title: "maimaiちゃんのテーマ", category: .maimai),
    SongModel(id: "m_149", title: "Pixel Voyage", category: .maimai),
    SongModel(id: "m_150", title: "maiム・maiム feat.週刊少年マガジン", category: .maimai),
    SongModel(id: "m_151", title: "タカハせ！名人マン", category: .maimai),
    SongModel(id: "m_152", title: "みんなのマイマイマー", category: .maimai),
    SongModel(id: "m_153", title: "welcome to maimai!! with マイマイマー", category: .maimai),
    SongModel(id: "m_154", title: "ぐるぐるWASH！コインランドリー・ディスコ", category: .maimai),
    SongModel(id: "m_155", title: "Sweets×Sweets", category: .maimai),
    SongModel(id: "m_156", title: "虹と太陽", category: .maimai),
    SongModel(id: "m_157", title: "Color My World", category: .maimai),
    SongModel(id: "m_158", title: "True Love Song", category: .maimai),
    SongModel(id: "m_159", title: "ソーラン☆節", category: .maimai),
    SongModel(id: "m_160", title: "おても☆Yan", category: .maimai),
    SongModel(id: "m_161", title: "炭★坑★節", category: .maimai),
    SongModel(id: "m_162", title: "ネコ日和。", category: .maimai),
    SongModel(id: "m_163", title: "犬日和。", category: .maimai),
    SongModel(id: "m_164", title: "Endless World", category: .maimai),
    SongModel(id: "m_165", title: "Backyun! －悪い女－", category: .maimai),
    SongModel(id: "m_166", title: "BaBan!! －甘い罠－", category: .maimai),
    SongModel(id: "m_167", title: "オレンジの夏", category: .maimai),
    SongModel(id: "m_168", title: "ぴぴぱぷぅ！", category: .maimai),
    SongModel(id: "m_169", title: "炎歌 -ほむらうた-", category: .maimai),
    SongModel(id: "m_170", title: "泣き虫O'clock", category: .maimai),
    SongModel(id: "m_171", title: "ジングルベル", category: .maimai),
    SongModel(id: "m_172", title: "VERTeX", category: .maimai),
    SongModel(id: "m_173", title: "ワードワードワード", category: .maimai),
    SongModel(id: "m_174", title: "Stardust Memories", category: .maimai),
    SongModel(id: "m_175", title: "Flashkick", category: .maimai),
    SongModel(id: "m_176", title: "STEEL TRANSONIC", category: .maimai),
    SongModel(id: "m_177", title: "My My My", category: .maimai),
    SongModel(id: "m_178", title: "ブレインジャックシンドローム", category: .maimai),
    SongModel(id: "m_179", title: "シエルブルーマルシェ", category: .maimai),
    SongModel(id: "m_180", title: "Ututu", category: .maimai),
    SongModel(id: "m_181", title: "共鳴", category: .maimai),
    SongModel(id: "m_182", title: "渦状銀河のシンフォニエッタ", category: .maimai),
    SongModel(id: "m_183", title: "GRÄNDIR", category: .maimai),
    SongModel(id: "m_184", title: "封焔の135秒", category: .maimai),
    SongModel(id: "m_185", title: "ぼくたちいつでも　しゅわっしゅわ！", category: .maimai),
    SongModel(id: "m_186", title: "Jörqer", category: .maimai),
    SongModel(id: "m_187", title: "Sqlupp (Camellia's \"Sqleipd*Hiytex\" Remix)", category: .maimai),
    SongModel(id: "m_188", title: "Boys O’Clock", category: .maimai),
    SongModel(id: "m_189", title: "居並ぶ穀物と溜息まじりの運送屋", category: .maimai),
    SongModel(id: "m_190", title: "ARAIS", category: .maimai),
    SongModel(id: "m_191", title: "Beautiful Future", category: .maimai),
    SongModel(id: "m_192", title: "Mutation", category: .maimai),
    SongModel(id: "m_193", title: "Aetheric Energy", category: .maimai),
    SongModel(id: "m_194", title: "Komplexe", category: .maimai),
    SongModel(id: "m_195", title: "≠彡\"/了→", category: .maimai),
    SongModel(id: "m_196", title: "シアトリカル・ケース", category: .maimai),
    SongModel(id: "m_197", title: "REAL VOICE", category: .maimai),
    SongModel(id: "m_198", title: "オリフィス", category: .maimai),
    SongModel(id: "m_199", title: "ユメヒバナ", category: .maimai),
    SongModel(id: "m_200", title: "パラボラ", category: .maimai),
    SongModel(id: "m_201", title: "BREaK! BREaK! BREaK!", category: .maimai),
    SongModel(id: "m_202", title: "Regulus", category: .maimai),
    SongModel(id: "m_203", title: "ワンダーシャッフェンの法則", category: .maimai),
    SongModel(id: "m_204", title: "BIRTH", category: .maimai),
    SongModel(id: "m_205", title: "時計の国のジェミニ", category: .maimai),
    SongModel(id: "m_206", title: "Xenovcipher", category: .maimai),
    SongModel(id: "m_207", title: "VANTABLACK RAVER", category: .maimai),
    SongModel(id: "m_208", title: "Heavenly Blast", category: .maimai),
    SongModel(id: "m_209", title: "Paradisoda", category: .maimai),
    SongModel(id: "m_210", title: "届かない花束", category: .maimai),
    SongModel(id: "m_211", title: "ステップアンドライム", category: .maimai),
    SongModel(id: "m_212", title: "星めぐり、果ての君へ。", category: .maimai),
    SongModel(id: "m_213", title: "スローアライズ", category: .maimai),
    SongModel(id: "m_214", title: "生命不詳", category: .maimai),
    SongModel(id: "m_215", title: "チエルカ／エソテリカ", category: .maimai),
    SongModel(id: "m_216", title: "Starry Colors", category: .maimai),
    SongModel(id: "m_217", title: "VIIIbit Explorer", category: .maimai),
    SongModel(id: "m_218", title: "Never Give Up!", category: .maimai),
    SongModel(id: "m_219", title: "ほしぞらスペクタクル", category: .maimai),
    SongModel(id: "m_220", title: "蒼穹舞楽", category: .maimai),
    SongModel(id: "m_221", title: "Last Samurai", category: .maimai),
    SongModel(id: "m_222", title: "AMABIE", category: .maimai),
    SongModel(id: "m_223", title: "アンビバレンス", category: .maimai),
    SongModel(id: "m_224", title: "噛み係", category: .maimai),
    SongModel(id: "m_225", title: "NAGAREBOSHI☆ROCKET", category: .maimai),
    SongModel(id: "m_226", title: "とびだせ！TO THE COSMIC!!", category: .maimai),
    SongModel(id: "m_227", title: "トリアージ", category: .maimai),
    SongModel(id: "m_228", title: "Lia=Fail", category: .maimai),
    SongModel(id: "m_229", title: "星詠みとデスペラード", category: .maimai),
    SongModel(id: "m_230", title: "BLACK SWAN", category: .maimai),
    SongModel(id: "m_231", title: "U&iVERSE -銀河鸞翔-", category: .maimai),
    SongModel(id: "m_232", title: "華の集落、秋のお届け", category: .maimai),
    SongModel(id: "m_233", title: "GIGANTØMAKHIA", category: .maimai),
    SongModel(id: "m_234", title: "Round Round Spinning Around", category: .maimai),
    SongModel(id: "m_235", title: "Raven Emperor", category: .maimai),
    SongModel(id: "m_236", title: "Alcyone", category: .maimai),
    SongModel(id: "m_237", title: "Yorugao", category: .maimai),
    SongModel(id: "m_238", title: "前衛的Landscape", category: .maimai),
    SongModel(id: "m_239", title: "躯樹の墓守", category: .maimai),
    SongModel(id: "m_240", title: "ヨミビトシラズ", category: .maimai),
    SongModel(id: "m_241", title: "Trick tear", category: .maimai),
    SongModel(id: "m_242", title: "sølips", category: .maimai),
    SongModel(id: "m_243", title: "パラマウント☆ショータイム！！", category: .maimai),
    SongModel(id: "m_244", title: "ｉｓｏｐｈｏｔｅ", category: .maimai),
    SongModel(id: "m_245", title: "WiPE OUT MEMORIES", category: .maimai),
    SongModel(id: "m_246", title: "Strive against fate", category: .maimai),
    SongModel(id: "m_247", title: "ミルキースター・シューティングスター", category: .maimai),
    SongModel(id: "m_248", title: "OTOGEMA", category: .maimai),
    SongModel(id: "m_249", title: "遺伝子レベル∞スパイラル", category: .maimai),
    SongModel(id: "m_250", title: "パーフェクション", category: .maimai),
    SongModel(id: "m_251", title: "Irresistible", category: .maimai),
    SongModel(id: "m_252", title: "HAGAKIRI", category: .maimai),
    SongModel(id: "m_253", title: "HECATONCHEIR", category: .maimai),
    SongModel(id: "m_254", title: "N3V3R G3T OV3R", category: .maimai),
    SongModel(id: "m_255", title: "デーモンベット", category: .maimai),
    SongModel(id: "m_256", title: "星空パーティーチューン", category: .maimai),
    SongModel(id: "m_257", title: "チューリングの跡", category: .maimai),
    SongModel(id: "m_258", title: "Swift Swing", category: .maimai),
    SongModel(id: "m_259", title: "Sage", category: .maimai),
    SongModel(id: "m_260", title: "Jouez Avec Moi?", category: .maimai),
    SongModel(id: "m_261", title: "Metamorphosism", category: .maimai),
    SongModel(id: "m_262", title: "白花の天使", category: .maimai),
    SongModel(id: "m_263", title: "World's end loneliness", category: .maimai),
    SongModel(id: "m_264", title: "ホシシズク", category: .maimai),
    SongModel(id: "m_265", title: "Rainbow Rush Story", category: .maimai),
    SongModel(id: "m_266", title: "Tricolor⁂circuS", category: .maimai),
    SongModel(id: "m_267", title: "[X]", category: .maimai),
    SongModel(id: "m_268", title: "mystique as iris", category: .maimai),
    SongModel(id: "m_269", title: "分解収束テイル", category: .maimai),
    SongModel(id: "m_270", title: "You Mean the World to Me", category: .maimai),
    SongModel(id: "m_271", title: "Neon Kingdom", category: .maimai),
    SongModel(id: "m_272", title: "Rising on the horizon", category: .maimai),
    SongModel(id: "m_273", title: "ViRTUS", category: .maimai),
    SongModel(id: "m_274", title: "#狂った民族２ PRAVARGYAZOOQA", category: .maimai),
    SongModel(id: "m_275", title: "VSpook!", category: .maimai),
    SongModel(id: "m_276", title: "RIFFRAIN", category: .maimai),
    SongModel(id: "m_277", title: "ピリオドサイン", category: .maimai),
    SongModel(id: "m_278", title: "群青シグナル", category: .maimai),
    SongModel(id: "m_279", title: "Beat Opera op.1", category: .maimai),
    SongModel(id: "m_280", title: "星見草", category: .maimai),
    SongModel(id: "m_281", title: "Falling", category: .maimai),
    SongModel(id: "m_282", title: "\"411Ψ892\"", category: .maimai),
    SongModel(id: "m_283", title: "康莊大道", category: .maimai),
    SongModel(id: "m_284", title: "トノサマビーム", category: .maimai),
    SongModel(id: "m_285", title: "ツムギボシ", category: .maimai),
    SongModel(id: "m_286", title: "Comet Panto Men!", category: .maimai),
    SongModel(id: "m_287", title: "enchanted wanderer", category: .maimai),
    SongModel(id: "m_288", title: "VeRForTe αRtE:VEiN", category: .maimai),
    SongModel(id: "m_289", title: "リフヴェイン", category: .maimai),
    SongModel(id: "m_290", title: "宵の鳥", category: .maimai),
    SongModel(id: "m_291", title: "Kairos", category: .maimai),
    SongModel(id: "m_292", title: "ヱデン", category: .maimai),
    SongModel(id: "m_293", title: "モ°ルモ°ル (MZK Skippin' Remix)", category: .maimai),
    SongModel(id: "m_294", title: "アンバークロニクル", category: .maimai),
    SongModel(id: "m_295", title: "にゃーにゃー冒険譚", category: .maimai),
    SongModel(id: "m_296", title: "ここからはじまるプロローグ。 (Kanon Remix)", category: .maimai),
    SongModel(id: "m_297", title: "VERTeX (rintaro soma deconstructed remix)", category: .maimai),
    SongModel(id: "m_298", title: "超熊猫的周遊記（ワンダーパンダートラベラー）", category: .maimai),
    SongModel(id: "m_299", title: "系ぎて", category: .maimai),
    SongModel(id: "m_300", title: "Horoscope Express", category: .maimai),
    SongModel(id: "m_301", title: "Party☆People☆Princess", category: .maimai),
    SongModel(id: "m_302", title: "Latent Kingdom", category: .maimai),
    SongModel(id: "m_303", title: "隠密あんみつDX", category: .maimai),
    SongModel(id: "m_304", title: "地球", category: .maimai),
    SongModel(id: "m_305", title: "Churros Parlor", category: .maimai),
    SongModel(id: "m_306", title: "NOIZY BOUNCE", category: .maimai),
    SongModel(id: "m_307", title: "サンバディ！", category: .maimai),
    SongModel(id: "m_308", title: "Mystic Parade", category: .maimai),
    SongModel(id: "m_309", title: "KHYMΞXΛ", category: .maimai),
    SongModel(id: "m_310", title: "POWER OF UNITY", category: .maimai),
    SongModel(id: "m_311", title: "ぽわわん劇場", category: .maimai),
    SongModel(id: "m_312", title: "Energizing Flame", category: .maimai),
    SongModel(id: "m_313", title: "my flow", category: .maimai),
    SongModel(id: "m_314", title: "Cry Cry Cry", category: .maimai),
    SongModel(id: "m_315", title: "raputa", category: .maimai),
    SongModel(id: "m_316", title: "フタタビ", category: .maimai),
    SongModel(id: "m_317", title: "ふらふらふら、", category: .maimai),
    SongModel(id: "m_318", title: "フェイクフェイス・フェイルセイフ", category: .maimai),
    SongModel(id: "m_319", title: "シックスプラン", category: .maimai),
    SongModel(id: "m_320", title: "Redemption", category: .maimai),
    SongModel(id: "m_321", title: "Straight into the lights", category: .maimai),
    SongModel(id: "m_322", title: "Ether Second", category: .maimai),
    SongModel(id: "m_323", title: "The Great Banquet", category: .maimai),
])

// niconicoAndVocaloid songs
songs.append(contentsOf: [
    SongModel(id: "n_1", title: "アンドロイドガール", category: .niconicoAndVocaloid),
    SongModel(id: "n_2", title: "スロウダウナー", category: .niconicoAndVocaloid),
    SongModel(id: "n_3", title: "ビターチョコデコレーション", category: .niconicoAndVocaloid),
    SongModel(id: "n_4", title: "スターリースカイ☆パレード", category: .niconicoAndVocaloid),
    SongModel(id: "n_5", title: "だれかの心臓になれたなら", category: .niconicoAndVocaloid),
    SongModel(id: "n_6", title: "グリーンライツ・セレナーデ", category: .niconicoAndVocaloid),
    SongModel(id: "n_7", title: "METEOR", category: .niconicoAndVocaloid),
    SongModel(id: "n_8", title: "だからパンを焼いたんだ", category: .niconicoAndVocaloid),
    SongModel(id: "n_9", title: "太陽系デスコ", category: .niconicoAndVocaloid),
    SongModel(id: "n_10", title: "彗星ハネムーン", category: .niconicoAndVocaloid),
    SongModel(id: "n_11", title: "ダンスロボットダンス", category: .niconicoAndVocaloid),
    SongModel(id: "n_12", title: "エイリアンエイリアン", category: .niconicoAndVocaloid),
    SongModel(id: "n_13", title: "パーフェクト生命", category: .niconicoAndVocaloid),
    SongModel(id: "n_14", title: "Seyana. ～何でも言うことを聞いてくれるアカネチャン～", category: .niconicoAndVocaloid),
    SongModel(id: "n_15", title: "アカリがやってきたぞっ", category: .niconicoAndVocaloid),
    SongModel(id: "n_16", title: "幾望の月", category: .niconicoAndVocaloid),
    SongModel(id: "n_17", title: "キミノヨゾラ哨戒班", category: .niconicoAndVocaloid),
    SongModel(id: "n_18", title: "ウミユリ海底譚", category: .niconicoAndVocaloid),
    SongModel(id: "n_19", title: "白ゆき", category: .niconicoAndVocaloid),
    SongModel(id: "n_20", title: "イカサマライフゲイム", category: .niconicoAndVocaloid),
    SongModel(id: "n_21", title: "敗北の少年", category: .niconicoAndVocaloid),
    SongModel(id: "n_22", title: "インビジブル", category: .niconicoAndVocaloid),
    SongModel(id: "n_23", title: "人生リセットボタン", category: .niconicoAndVocaloid),
    SongModel(id: "n_24", title: "リンカーネイション", category: .niconicoAndVocaloid),
    SongModel(id: "n_25", title: "六兆年と一夜物語", category: .niconicoAndVocaloid),
    SongModel(id: "n_26", title: "フラジール", category: .niconicoAndVocaloid),
    SongModel(id: "n_27", title: "命ばっかり", category: .niconicoAndVocaloid),
    SongModel(id: "n_28", title: "フィクサー", category: .niconicoAndVocaloid),
    SongModel(id: "n_29", title: "チュルリラ・チュルリラ・ダッダッダ！", category: .niconicoAndVocaloid),
    SongModel(id: "n_30", title: "サヨナラチェーンソー", category: .niconicoAndVocaloid),
    SongModel(id: "n_31", title: "39みゅーじっく！", category: .niconicoAndVocaloid),
    SongModel(id: "n_32", title: "ロキ", category: .niconicoAndVocaloid),
    SongModel(id: "n_33", title: "バレリーコ", category: .niconicoAndVocaloid),
    SongModel(id: "n_34", title: "いーあるふぁんくらぶ", category: .niconicoAndVocaloid),
    SongModel(id: "n_35", title: "だんだん早くなる", category: .niconicoAndVocaloid),
    SongModel(id: "n_36", title: "恋愛裁判", category: .niconicoAndVocaloid),
    SongModel(id: "n_37", title: "からくりピエロ", category: .niconicoAndVocaloid),
    SongModel(id: "n_38", title: "脳漿炸裂ガール", category: .niconicoAndVocaloid),
    SongModel(id: "n_39", title: "カゲロウデイズ", category: .niconicoAndVocaloid),
    SongModel(id: "n_40", title: "夜咄ディセイブ", category: .niconicoAndVocaloid),
    SongModel(id: "n_41", title: "アウターサイエンス", category: .niconicoAndVocaloid),
    SongModel(id: "n_42", title: "アディショナルメモリー", category: .niconicoAndVocaloid),
    SongModel(id: "n_43", title: "砂の惑星 feat. HATSUNE MIKU", category: .niconicoAndVocaloid),
    SongModel(id: "n_44", title: "ドーナツホール", category: .niconicoAndVocaloid),
    SongModel(id: "n_45", title: "マトリョシカ", category: .niconicoAndVocaloid),
    SongModel(id: "n_46", title: "パンダヒーロー", category: .niconicoAndVocaloid),
    SongModel(id: "n_47", title: "WORLD'S END UMBRELLA", category: .niconicoAndVocaloid),
    SongModel(id: "n_48", title: "結ンデ開イテ羅刹ト骸", category: .niconicoAndVocaloid),
    SongModel(id: "n_49", title: "ゴーゴー幽霊船", category: .niconicoAndVocaloid),
    SongModel(id: "n_50", title: "アンノウン・マザーグース", category: .niconicoAndVocaloid),
    SongModel(id: "n_51", title: "アンハッピーリフレイン", category: .niconicoAndVocaloid),
    SongModel(id: "n_52", title: "裏表ラバーズ", category: .niconicoAndVocaloid),
    SongModel(id: "n_53", title: "ローリンガール", category: .niconicoAndVocaloid),
    SongModel(id: "n_54", title: "ワールズエンド・ダンスホール", category: .niconicoAndVocaloid),
    SongModel(id: "n_55", title: "ゴーストルール", category: .niconicoAndVocaloid),
    SongModel(id: "n_56", title: "モザイクロール", category: .niconicoAndVocaloid),
    SongModel(id: "n_57", title: "ありふれたせかいせいふく", category: .niconicoAndVocaloid),
    SongModel(id: "n_58", title: "腐れ外道とチョコレゐト", category: .niconicoAndVocaloid),
    SongModel(id: "n_59", title: "+♂", category: .niconicoAndVocaloid),
    SongModel(id: "n_60", title: "セツナトリップ", category: .niconicoAndVocaloid),
    SongModel(id: "n_61", title: "放課後ストライド", category: .niconicoAndVocaloid),
    SongModel(id: "n_62", title: "このピアノでお前を8759632145回ぶん殴る", category: .niconicoAndVocaloid),
    SongModel(id: "n_63", title: "やめろ！聴くな！", category: .niconicoAndVocaloid),
    SongModel(id: "n_64", title: "メランコリック", category: .niconicoAndVocaloid),
    SongModel(id: "n_65", title: "ZIGG-ZAGG", category: .niconicoAndVocaloid),
    SongModel(id: "n_66", title: "I ♥", category: .niconicoAndVocaloid),
    SongModel(id: "n_67", title: "ラブチーノ", category: .niconicoAndVocaloid),
    SongModel(id: "n_68", title: "スイートマジック", category: .niconicoAndVocaloid),
    SongModel(id: "n_69", title: "リリリリ★バーニングナイト", category: .niconicoAndVocaloid),
    SongModel(id: "n_70", title: "イアイア★ナイトオブデザイア", category: .niconicoAndVocaloid),
    SongModel(id: "n_71", title: "ルカルカ★ナイトフィーバー", category: .niconicoAndVocaloid),
    SongModel(id: "n_72", title: "メグメグ☆ファイアーエンドレスナイト", category: .niconicoAndVocaloid),
    SongModel(id: "n_73", title: "深海少女", category: .niconicoAndVocaloid),
    SongModel(id: "n_74", title: "トルコ行進曲 - オワタ＼(^o^)／", category: .niconicoAndVocaloid),
    SongModel(id: "n_75", title: "Sweetiex2", category: .niconicoAndVocaloid),
    SongModel(id: "n_76", title: "shake it!", category: .niconicoAndVocaloid),
    SongModel(id: "n_77", title: "Heart Beats", category: .niconicoAndVocaloid),
    SongModel(id: "n_78", title: "初音ミクの激唱", category: .niconicoAndVocaloid),
    SongModel(id: "n_79", title: "初音ミクの消失", category: .niconicoAndVocaloid),
    SongModel(id: "n_80", title: "終点", category: .niconicoAndVocaloid),
    SongModel(id: "n_81", title: "Tell Your World", category: .niconicoAndVocaloid),
    SongModel(id: "n_82", title: "メルティランドナイトメア", category: .niconicoAndVocaloid),
    SongModel(id: "n_83", title: "メルト", category: .niconicoAndVocaloid),
    SongModel(id: "n_84", title: "デンパラダイム", category: .niconicoAndVocaloid),
    SongModel(id: "n_85", title: "骸骨楽団とリリア", category: .niconicoAndVocaloid),
    SongModel(id: "n_86", title: "星屑ユートピア", category: .niconicoAndVocaloid),
    SongModel(id: "n_87", title: "アマツキツネ", category: .niconicoAndVocaloid),
    SongModel(id: "n_88", title: "Strobe♡Girl", category: .niconicoAndVocaloid),
    SongModel(id: "n_89", title: "ナイトメア☆パーティーナイト", category: .niconicoAndVocaloid),
    SongModel(id: "n_90", title: "はやくそれになりたい！", category: .niconicoAndVocaloid),
    SongModel(id: "n_91", title: "おねがいダーリン", category: .niconicoAndVocaloid),
    SongModel(id: "n_92", title: "フリィダム ロリィタ", category: .niconicoAndVocaloid),
    SongModel(id: "n_93", title: "幸せになれる隠しコマンドがあるらしい", category: .niconicoAndVocaloid),
    SongModel(id: "n_94", title: "しねばいいのに", category: .niconicoAndVocaloid),
    SongModel(id: "n_95", title: "キレキャリオン", category: .niconicoAndVocaloid),
    SongModel(id: "n_96", title: "ドクハク", category: .niconicoAndVocaloid),
    SongModel(id: "n_97", title: "アルカリレットウセイ", category: .niconicoAndVocaloid),
    SongModel(id: "n_98", title: "ARROW", category: .niconicoAndVocaloid),
    SongModel(id: "n_99", title: "ヘルシーエンド", category: .niconicoAndVocaloid),
    SongModel(id: "n_100", title: "ロストワンの号哭", category: .niconicoAndVocaloid),
    SongModel(id: "n_101", title: "天ノ弱", category: .niconicoAndVocaloid),
    SongModel(id: "n_102", title: "吉原ラメント", category: .niconicoAndVocaloid),
    SongModel(id: "n_103", title: "生きてるおばけは生きている", category: .niconicoAndVocaloid),
    SongModel(id: "n_104", title: "踊れオーケストラ", category: .niconicoAndVocaloid),
    SongModel(id: "n_105", title: "赤心性：カマトト荒療治", category: .niconicoAndVocaloid),
    SongModel(id: "n_106", title: "イノコリ先生", category: .niconicoAndVocaloid),
    SongModel(id: "n_107", title: "ECHO", category: .niconicoAndVocaloid),
    SongModel(id: "n_108", title: "東京リアルワールド", category: .niconicoAndVocaloid),
    SongModel(id: "n_109", title: "M.S.S.Planet", category: .niconicoAndVocaloid),
    SongModel(id: "n_110", title: "不毛！", category: .niconicoAndVocaloid),
    SongModel(id: "n_111", title: "ネトゲ廃人シュプレヒコール", category: .niconicoAndVocaloid),
    SongModel(id: "n_112", title: "StargazeR", category: .niconicoAndVocaloid),
    SongModel(id: "n_113", title: "みくみくにしてあげる♪【してやんよ】", category: .niconicoAndVocaloid),
    SongModel(id: "n_114", title: "ぽっぴっぽー", category: .niconicoAndVocaloid),
    SongModel(id: "n_115", title: "Nyan Cat EX", category: .niconicoAndVocaloid),
    SongModel(id: "n_116", title: "どうしてこうなった", category: .niconicoAndVocaloid),
    SongModel(id: "n_117", title: "magician's operation", category: .niconicoAndVocaloid),
    SongModel(id: "n_118", title: "教えて!! 魔法のLyric", category: .niconicoAndVocaloid),
    SongModel(id: "n_119", title: "おちゃめ機能", category: .niconicoAndVocaloid),
    SongModel(id: "n_120", title: "BAD∞END∞NIGHT", category: .niconicoAndVocaloid),
    SongModel(id: "n_121", title: "ロミオとシンデレラ", category: .niconicoAndVocaloid),
    SongModel(id: "n_122", title: "ダンシング☆サムライ", category: .niconicoAndVocaloid),
    SongModel(id: "n_123", title: "ハロ／ハワユ", category: .niconicoAndVocaloid),
    SongModel(id: "n_124", title: "林檎華憐歌", category: .niconicoAndVocaloid),
    SongModel(id: "n_125", title: "ないせんのうた", category: .niconicoAndVocaloid),
    SongModel(id: "n_126", title: "木彫り鯰と右肩ゾンビ", category: .niconicoAndVocaloid),
    SongModel(id: "n_127", title: "デッドレッドガールズ", category: .niconicoAndVocaloid),
    SongModel(id: "n_128", title: "One Step Ahead", category: .niconicoAndVocaloid),
    SongModel(id: "n_129", title: "Link", category: .niconicoAndVocaloid),
    SongModel(id: "n_130", title: "バッド・ダンス・ホール", category: .niconicoAndVocaloid),
    SongModel(id: "n_131", title: "quiet room", category: .niconicoAndVocaloid),
    SongModel(id: "n_132", title: "ロールプレイングゲーム", category: .niconicoAndVocaloid),
    SongModel(id: "n_133", title: "すーぱーぬこになりたい", category: .niconicoAndVocaloid),
    SongModel(id: "n_134", title: "立ち入り禁止", category: .niconicoAndVocaloid),
    SongModel(id: "n_135", title: "CocktaiL", category: .niconicoAndVocaloid),
    SongModel(id: "n_136", title: "ナンセンス文学", category: .niconicoAndVocaloid),
    SongModel(id: "n_137", title: "シャルル", category: .niconicoAndVocaloid),
    SongModel(id: "n_138", title: "おこちゃま戦争", category: .niconicoAndVocaloid),
    SongModel(id: "n_139", title: "拝啓ドッペルゲンガー", category: .niconicoAndVocaloid),
    SongModel(id: "n_140", title: "すーぱーぬこになれんかった", category: .niconicoAndVocaloid),
    SongModel(id: "n_141", title: "Catch the Wave", category: .niconicoAndVocaloid),
    SongModel(id: "n_142", title: "アスヘノBRAVE", category: .niconicoAndVocaloid),
    SongModel(id: "n_143", title: "深海シティアンダーグラウンド", category: .niconicoAndVocaloid),
    SongModel(id: "n_144", title: "表裏一体", category: .niconicoAndVocaloid),
    SongModel(id: "n_145", title: "クレイジー・ビート", category: .niconicoAndVocaloid),
    SongModel(id: "n_146", title: "グラーヴェ", category: .niconicoAndVocaloid),
    SongModel(id: "n_147", title: "バイオレンストリガー", category: .niconicoAndVocaloid),
    SongModel(id: "n_148", title: "KILLER B", category: .niconicoAndVocaloid),
    SongModel(id: "n_149", title: "命に嫌われている", category: .niconicoAndVocaloid),
    SongModel(id: "n_150", title: "乙女解剖", category: .niconicoAndVocaloid),
    SongModel(id: "n_151", title: "アンクローズ・ヒューマン", category: .niconicoAndVocaloid),
    SongModel(id: "n_152", title: "ベノム", category: .niconicoAndVocaloid),
    SongModel(id: "n_153", title: "絶対にチョコミントを食べるアオイチャン", category: .niconicoAndVocaloid),
    SongModel(id: "n_154", title: "絶え間なく藍色", category: .niconicoAndVocaloid),
    SongModel(id: "n_155", title: "とりあえずアナタがいなくなるまえに", category: .niconicoAndVocaloid),
    SongModel(id: "n_156", title: "デリヘル呼んだら君が来た", category: .niconicoAndVocaloid),
    SongModel(id: "n_157", title: "明星ギャラクティカ", category: .niconicoAndVocaloid),
    SongModel(id: "n_158", title: "ガランド", category: .niconicoAndVocaloid),
    SongModel(id: "n_159", title: "マネマネサイコトロピック", category: .niconicoAndVocaloid),
    SongModel(id: "n_160", title: "アスノヨゾラ哨戒班", category: .niconicoAndVocaloid),
    SongModel(id: "n_161", title: "二息歩行", category: .niconicoAndVocaloid),
    SongModel(id: "n_162", title: "頓珍漢の宴", category: .niconicoAndVocaloid),
    SongModel(id: "n_163", title: "ヒバナ", category: .niconicoAndVocaloid),
    SongModel(id: "n_164", title: "雨とペトラ", category: .niconicoAndVocaloid),
    SongModel(id: "n_165", title: "ネガティブ進化論", category: .niconicoAndVocaloid),
    SongModel(id: "n_166", title: "永遠にゲームで対戦したいキリタン", category: .niconicoAndVocaloid),
    SongModel(id: "n_167", title: "KING", category: .niconicoAndVocaloid),
    SongModel(id: "n_168", title: "幽霊東京", category: .niconicoAndVocaloid),
    SongModel(id: "n_169", title: "Alice in 冷凍庫", category: .niconicoAndVocaloid),
    SongModel(id: "n_170", title: "再会", category: .niconicoAndVocaloid),
    SongModel(id: "n_171", title: "約束", category: .niconicoAndVocaloid),
    SongModel(id: "n_172", title: "猫猫的宇宙論", category: .niconicoAndVocaloid),
    SongModel(id: "n_173", title: "アルティメットセンパイ", category: .niconicoAndVocaloid),
    SongModel(id: "n_174", title: "トラフィック・ジャム", category: .niconicoAndVocaloid),
    SongModel(id: "n_175", title: "ラットが死んだnew words", category: .niconicoAndVocaloid),
    SongModel(id: "n_176", title: "阿吽のビーツ", category: .niconicoAndVocaloid),
    SongModel(id: "n_177", title: "グッバイ宣言", category: .niconicoAndVocaloid),
    SongModel(id: "n_178", title: "テレキャスタービーボーイ", category: .niconicoAndVocaloid),
    SongModel(id: "n_179", title: "僕は空気が嫁ない", category: .niconicoAndVocaloid),
    SongModel(id: "n_180", title: "デッドマンズバラッド", category: .niconicoAndVocaloid),
    SongModel(id: "n_181", title: "ポッピンキャンディ☆フィーバー！", category: .niconicoAndVocaloid),
    SongModel(id: "n_182", title: "どぅーまいべすと！", category: .niconicoAndVocaloid),
    SongModel(id: "n_183", title: "失敗作少女", category: .niconicoAndVocaloid),
    SongModel(id: "n_184", title: "ノイローゼ", category: .niconicoAndVocaloid),
    SongModel(id: "n_185", title: "悪魔の踊り方", category: .niconicoAndVocaloid),
    SongModel(id: "n_186", title: "春嵐", category: .niconicoAndVocaloid),
    SongModel(id: "n_187", title: "アカツキアライヴァル", category: .niconicoAndVocaloid),
    SongModel(id: "n_188", title: "リモコン", category: .niconicoAndVocaloid),
    SongModel(id: "n_189", title: "ラグトレイン", category: .niconicoAndVocaloid),
    SongModel(id: "n_190", title: "on the rocks", category: .niconicoAndVocaloid),
    SongModel(id: "n_191", title: "エンヴィーベイビー", category: .niconicoAndVocaloid),
    SongModel(id: "n_192", title: "ヴァンパイア", category: .niconicoAndVocaloid),
    SongModel(id: "n_193", title: "初音天地開闢神話", category: .niconicoAndVocaloid),
    SongModel(id: "n_194", title: "エゴロック", category: .niconicoAndVocaloid),
    SongModel(id: "n_195", title: "ジャンキーナイトタウンオーケストラ", category: .niconicoAndVocaloid),
    SongModel(id: "n_196", title: "終焉逃避行", category: .niconicoAndVocaloid),
    SongModel(id: "n_197", title: "ただ選択があった", category: .niconicoAndVocaloid),
    SongModel(id: "n_198", title: "39", category: .niconicoAndVocaloid),
    SongModel(id: "n_199", title: "弱虫モンブラン", category: .niconicoAndVocaloid),
    SongModel(id: "n_200", title: "ストリーミングハート", category: .niconicoAndVocaloid),
    SongModel(id: "n_201", title: "共感覚おばけ", category: .niconicoAndVocaloid),
    SongModel(id: "n_202", title: "妄想感傷代償連盟", category: .niconicoAndVocaloid),
    SongModel(id: "n_203", title: "ディカディズム", category: .niconicoAndVocaloid),
    SongModel(id: "n_204", title: "フォニイ", category: .niconicoAndVocaloid),
    SongModel(id: "n_205", title: "アニマル", category: .niconicoAndVocaloid),
    SongModel(id: "n_206", title: "ジレンマ", category: .niconicoAndVocaloid),
    SongModel(id: "n_207", title: "EYE", category: .niconicoAndVocaloid),
    SongModel(id: "n_208", title: "ヴィラン", category: .niconicoAndVocaloid),
    SongModel(id: "n_209", title: "マーシャル・マキシマイザー", category: .niconicoAndVocaloid),
    SongModel(id: "n_210", title: "秋の未確認生物", category: .niconicoAndVocaloid),
    SongModel(id: "n_211", title: "ボッカデラベリタ", category: .niconicoAndVocaloid),
    SongModel(id: "n_212", title: "『んっあっあっ。』", category: .niconicoAndVocaloid),
    SongModel(id: "n_213", title: "キュートなカノジョ", category: .niconicoAndVocaloid),
    SongModel(id: "n_214", title: "きゅうくらりん", category: .niconicoAndVocaloid),
    SongModel(id: "n_215", title: "回る空うさぎ", category: .niconicoAndVocaloid),
    SongModel(id: "n_216", title: "ロータスイーター", category: .niconicoAndVocaloid),
    SongModel(id: "n_217", title: "独りんぼエンヴィー", category: .niconicoAndVocaloid),
    SongModel(id: "n_218", title: "へべれけジャンキー", category: .niconicoAndVocaloid),
    SongModel(id: "n_219", title: "ロウワー", category: .niconicoAndVocaloid),
    SongModel(id: "n_220", title: "魔法少女とチョコレゐト", category: .niconicoAndVocaloid),
    SongModel(id: "n_221", title: "キャットラビング", category: .niconicoAndVocaloid),
    SongModel(id: "n_222", title: "神っぽいな", category: .niconicoAndVocaloid),
    SongModel(id: "n_223", title: "私のドッペルゲンガー", category: .niconicoAndVocaloid),
    SongModel(id: "n_224", title: "テオ", category: .niconicoAndVocaloid),
    SongModel(id: "n_225", title: "花となれ", category: .niconicoAndVocaloid),
    SongModel(id: "n_226", title: "ド屑", category: .niconicoAndVocaloid),
    SongModel(id: "n_227", title: "絶対敵対メチャキライヤー", category: .niconicoAndVocaloid),
    SongModel(id: "n_228", title: "ずんだもんの朝食　〜目覚ましずんラップ〜", category: .niconicoAndVocaloid),
    SongModel(id: "n_229", title: "あなたは世界の終わりにずんだを食べるのだ", category: .niconicoAndVocaloid),
    SongModel(id: "n_230", title: "まにまに", category: .niconicoAndVocaloid),
    SongModel(id: "n_231", title: "感情ディシーブ", category: .niconicoAndVocaloid),
    SongModel(id: "n_232", title: "熱異常", category: .niconicoAndVocaloid),
    SongModel(id: "n_233", title: "1000年生きてる", category: .niconicoAndVocaloid),
    SongModel(id: "n_234", title: "IMAWANOKIWA", category: .niconicoAndVocaloid),
    SongModel(id: "n_235", title: "バグ", category: .niconicoAndVocaloid),
    SongModel(id: "n_236", title: "星界ちゃんと可不ちゃんのおつかい合騒曲", category: .niconicoAndVocaloid),
    SongModel(id: "n_237", title: "ノンブレス・オブリージュ", category: .niconicoAndVocaloid),
    SongModel(id: "n_238", title: "トンデモワンダーズ", category: .niconicoAndVocaloid),
    SongModel(id: "n_239", title: "ジェヘナ", category: .niconicoAndVocaloid),
    SongModel(id: "n_240", title: "ツギハギスタッカート", category: .niconicoAndVocaloid),
    SongModel(id: "n_241", title: "＊ハロー、プラネット。", category: .niconicoAndVocaloid),
    SongModel(id: "n_242", title: "QUEEN", category: .niconicoAndVocaloid),
    SongModel(id: "n_243", title: "天使の翼。", category: .niconicoAndVocaloid),
    SongModel(id: "n_244", title: "さよならプリンセス", category: .niconicoAndVocaloid),
])

// gameAndVariety songs
songs.append(contentsOf: [
    SongModel(id: "g_1", title: "BATTLE NO.1", category: .gameAndVariety),
    SongModel(id: "g_2", title: "Black Lair", category: .gameAndVariety),
    SongModel(id: "g_3", title: "FLOWER", category: .gameAndVariety),
    SongModel(id: "g_4", title: "Scars of FAUNA", category: .gameAndVariety),
    SongModel(id: "g_5", title: "極圏", category: .gameAndVariety),
    SongModel(id: "g_6", title: "きたさいたま2000", category: .gameAndVariety),
    SongModel(id: "g_7", title: "Ignis Danse", category: .gameAndVariety),
    SongModel(id: "g_8", title: "夜明けまであと３秒", category: .gameAndVariety),
    SongModel(id: "g_9", title: "セイクリッド　ルイン", category: .gameAndVariety),
    SongModel(id: "g_10", title: "Got more raves？", category: .gameAndVariety),
    SongModel(id: "g_11", title: "FUJIN Rumble", category: .gameAndVariety),
    SongModel(id: "g_12", title: "Scarlet Lance", category: .gameAndVariety),
    SongModel(id: "g_13", title: "プナイプナイせんそう", category: .gameAndVariety),
    SongModel(id: "g_14", title: "Halcyon", category: .gameAndVariety),
    SongModel(id: "g_15", title: "サンバランド", category: .gameAndVariety),
    SongModel(id: "g_16", title: "End Time", category: .gameAndVariety),
    SongModel(id: "g_17", title: "Altale", category: .gameAndVariety),
    SongModel(id: "g_18", title: "Destr0yer", category: .gameAndVariety),
    SongModel(id: "g_19", title: "L4TS:2018 (feat. あひる & KTA)", category: .gameAndVariety),
    SongModel(id: "g_20", title: "B.M.S.", category: .gameAndVariety),
    SongModel(id: "g_21", title: "ENERGY SYNERGY MATRIX", category: .gameAndVariety),
    SongModel(id: "g_22", title: "FREEDOM DiVE (tpz Overcute Remix)", category: .gameAndVariety),
    SongModel(id: "g_23", title: "Brain Power", category: .gameAndVariety),
    SongModel(id: "g_24", title: "Credits", category: .gameAndVariety),
    SongModel(id: "g_25", title: "MilK", category: .gameAndVariety),
    SongModel(id: "g_26", title: "ULTRA B+K", category: .gameAndVariety),
    SongModel(id: "g_27", title: "GO BACK 2 YOUR RAVE", category: .gameAndVariety),
    SongModel(id: "g_28", title: "B.B.K.K.B.K.K.", category: .gameAndVariety),
    SongModel(id: "g_29", title: "魔法少女になるしかねぇ", category: .gameAndVariety),
    SongModel(id: "g_30", title: "人里に下ったアタイがいつの間にか社畜になっていた件", category: .gameAndVariety),
    SongModel(id: "g_31", title: "Maxi", category: .gameAndVariety),
    SongModel(id: "g_32", title: "KISS CANDY FLAVOR", category: .gameAndVariety),
    SongModel(id: "g_33", title: "conflict", category: .gameAndVariety),
    SongModel(id: "g_34", title: "EVERGREEN", category: .gameAndVariety),
    SongModel(id: "g_35", title: "Party 4U ”holy nite mix”", category: .gameAndVariety),
    SongModel(id: "g_36", title: "GOODMEN", category: .gameAndVariety),
    SongModel(id: "g_37", title: "Sakura Fubuki", category: .gameAndVariety),
    SongModel(id: "g_38", title: "METATRON", category: .gameAndVariety),
    SongModel(id: "g_39", title: "オモイヨシノ", category: .gameAndVariety),
    SongModel(id: "g_40", title: "L9", category: .gameAndVariety),
    SongModel(id: "g_41", title: "Good Bye, Mr. Jack", category: .gameAndVariety),
    SongModel(id: "g_42", title: "Jack-the-Ripper◆", category: .gameAndVariety),
    SongModel(id: "g_43", title: "DRAGONLADY", category: .gameAndVariety),
    SongModel(id: "g_44", title: "レッツゴー!陰陽師", category: .gameAndVariety),
    SongModel(id: "g_45", title: "オパ! オパ! RACER -GMT mashup-", category: .gameAndVariety),
    SongModel(id: "g_46", title: "電車で電車でOPA!OPA!OPA! -GMT mashup-", category: .gameAndVariety),
    SongModel(id: "g_47", title: "リッジでリッジでGO!GO!GO! -GMT mashup-", category: .gameAndVariety),
    SongModel(id: "g_48", title: "電車で電車でGO!GO!GO!GC! -GMT remix-", category: .gameAndVariety),
    SongModel(id: "g_49", title: "RIDGE RACER STEPS -GMT remix-", category: .gameAndVariety),
    SongModel(id: "g_50", title: "ファンタジーゾーン OPA-OPA! -GMT remix-", category: .gameAndVariety),
    SongModel(id: "g_51", title: "DADDY MULK -Groove remix-", category: .gameAndVariety),
    SongModel(id: "g_52", title: "デコボコ体操第二", category: .gameAndVariety),
    SongModel(id: "g_53", title: "Let's Go Away", category: .gameAndVariety),
    SongModel(id: "g_54", title: "Conquista Ciela", category: .gameAndVariety),
    SongModel(id: "g_55", title: "Fist Bump", category: .gameAndVariety),
    SongModel(id: "g_56", title: "Reach For The Stars", category: .gameAndVariety),
    SongModel(id: "g_57", title: "Live & Learn", category: .gameAndVariety),
    SongModel(id: "g_58", title: "Back 2 Back", category: .gameAndVariety),
    SongModel(id: "g_59", title: "Windy Hill -Zone 1", category: .gameAndVariety),
    SongModel(id: "g_60", title: "City Escape: Act1", category: .gameAndVariety),
    SongModel(id: "g_61", title: "Rooftop Run: Act1", category: .gameAndVariety),
    SongModel(id: "g_62", title: "終わりなき物語", category: .gameAndVariety),
    SongModel(id: "g_63", title: "Save This World νMIX", category: .gameAndVariety),
    SongModel(id: "g_64", title: "Living Universe", category: .gameAndVariety),
    SongModel(id: "g_65", title: "Ignite Infinity", category: .gameAndVariety),
    SongModel(id: "g_66", title: "Garden Of The Dragon", category: .gameAndVariety),
    SongModel(id: "g_67", title: "時空を超えて久しぶり！", category: .gameAndVariety),
    SongModel(id: "g_68", title: "Her Dream Is To Be A Fantastic Sorceress", category: .gameAndVariety),
    SongModel(id: "g_69", title: "キズナの物語", category: .gameAndVariety),
    SongModel(id: "g_70", title: "STAIRWAY TO GENERATION", category: .gameAndVariety),
    SongModel(id: "g_71", title: "Last Brave ～ Go to zero", category: .gameAndVariety),
    SongModel(id: "g_72", title: "Urban Crusher [Remix]", category: .gameAndVariety),
    SongModel(id: "g_73", title: "Catch The Future", category: .gameAndVariety),
    SongModel(id: "g_74", title: "awake", category: .gameAndVariety),
    SongModel(id: "g_75", title: "Terminal Storm", category: .gameAndVariety),
    SongModel(id: "g_76", title: "After Burner", category: .gameAndVariety),
    SongModel(id: "g_77", title: "Space Harrier Main Theme [Reborn]", category: .gameAndVariety),
    SongModel(id: "g_78", title: "Quartet Theme [Reborn]", category: .gameAndVariety),
    SongModel(id: "g_79", title: "Sky High [Reborn]", category: .gameAndVariety),
    SongModel(id: "g_80", title: "Like the Wind [Reborn]", category: .gameAndVariety),
    SongModel(id: "g_81", title: "YA･DA･YO [Reborn]", category: .gameAndVariety),
    SongModel(id: "g_82", title: "Crush On You", category: .gameAndVariety),
    SongModel(id: "g_83", title: "Sun Dance", category: .gameAndVariety),
    SongModel(id: "g_84", title: "In Chaos", category: .gameAndVariety),
    SongModel(id: "g_85", title: "Beat Of Mind", category: .gameAndVariety),
    SongModel(id: "g_86", title: "Natural Flow", category: .gameAndVariety),
    SongModel(id: "g_87", title: "JACKY [Remix]", category: .gameAndVariety),
    SongModel(id: "g_88", title: "Mysterious Destiny", category: .gameAndVariety),
    SongModel(id: "g_89", title: "Riders Of The Light", category: .gameAndVariety),
    SongModel(id: "g_90", title: "コトバ・カラフル", category: .gameAndVariety),
    SongModel(id: "g_91", title: "天国と地獄", category: .gameAndVariety),
    SongModel(id: "g_92", title: "きみのためなら死ねる", category: .gameAndVariety),
    SongModel(id: "g_93", title: "The Great Journey", category: .gameAndVariety),
    SongModel(id: "g_94", title: "Burning Hearts ～炎のANGEL～", category: .gameAndVariety),
    SongModel(id: "g_95", title: "かせげ！ジャリンコヒーロー", category: .gameAndVariety),
    SongModel(id: "g_96", title: "ココロスキャンのうた", category: .gameAndVariety),
    SongModel(id: "g_97", title: "超絶！Superlative", category: .gameAndVariety),
    SongModel(id: "g_98", title: "采配の刻 Power of order", category: .gameAndVariety),
    SongModel(id: "g_99", title: "DO RORO DERODERO ON DO RORO", category: .gameAndVariety),
    SongModel(id: "g_100", title: "源平大戦絵巻テーマソング", category: .gameAndVariety),
    SongModel(id: "g_101", title: "怪盗Rのテーマ", category: .gameAndVariety),
    SongModel(id: "g_102", title: "マリアをはげませ", category: .gameAndVariety),
    SongModel(id: "g_103", title: "SHOW TIME", category: .gameAndVariety),
    SongModel(id: "g_104", title: "円舞曲、君に", category: .gameAndVariety),
    SongModel(id: "g_105", title: "御旗のもとに", category: .gameAndVariety),
    SongModel(id: "g_106", title: "地上の戦士", category: .gameAndVariety),
    SongModel(id: "g_107", title: "檄！帝国華撃団(改)", category: .gameAndVariety),
    SongModel(id: "g_108", title: "Outlaw's Lullaby", category: .gameAndVariety),
    SongModel(id: "g_109", title: "Brand-new Japanesque", category: .gameAndVariety),
    SongModel(id: "g_110", title: "鼓動", category: .gameAndVariety),
    SongModel(id: "g_111", title: "神室雪月花", category: .gameAndVariety),
    SongModel(id: "g_112", title: "KONNANじゃないっ！", category: .gameAndVariety),
    SongModel(id: "g_113", title: "セガサターン起動音[H.][Remix]", category: .gameAndVariety),
    SongModel(id: "g_114", title: "アトロポスと最果の探究者", category: .gameAndVariety),
    SongModel(id: "g_115", title: "energy trixxx", category: .gameAndVariety),
    SongModel(id: "g_116", title: "NULCTRL", category: .gameAndVariety),
    SongModel(id: "g_117", title: "felys -final remix-", category: .gameAndVariety),
    SongModel(id: "g_118", title: "カラッポ・ノンフィクション", category: .gameAndVariety),
    SongModel(id: "g_119", title: "c.s.q.n.", category: .gameAndVariety),
    SongModel(id: "g_120", title: "emomomo", category: .gameAndVariety),
    SongModel(id: "g_121", title: "Grievous Lady", category: .gameAndVariety),
    SongModel(id: "g_122", title: "Ether Strike", category: .gameAndVariety),
    SongModel(id: "g_123", title: "Cyaegha", category: .gameAndVariety),
    SongModel(id: "g_124", title: "Re：End of a Dream", category: .gameAndVariety),
    SongModel(id: "g_125", title: "もぺもぺ", category: .gameAndVariety),
    SongModel(id: "g_126", title: "Sound Chimera", category: .gameAndVariety),
    SongModel(id: "g_127", title: "CO5M1C R4ILR0AD", category: .gameAndVariety),
    SongModel(id: "g_128", title: "Rush-More", category: .gameAndVariety),
    SongModel(id: "g_129", title: "MAKE IT FUNKY NOW", category: .gameAndVariety),
    SongModel(id: "g_130", title: "ベースラインやってる？笑", category: .gameAndVariety),
    SongModel(id: "g_131", title: "ヒミツCULT", category: .gameAndVariety),
    SongModel(id: "g_132", title: "Big Daddy", category: .gameAndVariety),
    SongModel(id: "g_133", title: "キラメキ居残り大戦争", category: .gameAndVariety),
    SongModel(id: "g_134", title: "Strange Bar", category: .gameAndVariety),
    SongModel(id: "g_135", title: "ALiVE", category: .gameAndVariety),
    SongModel(id: "g_136", title: "MEGATON KICK", category: .gameAndVariety),
    SongModel(id: "g_137", title: "LOSE CONTROL", category: .gameAndVariety),
    SongModel(id: "g_138", title: "Southern Cross", category: .gameAndVariety),
    SongModel(id: "g_139", title: "竹", category: .gameAndVariety),
    SongModel(id: "g_140", title: "スーパーシンメトリー", category: .gameAndVariety),
    SongModel(id: "g_141", title: "さんさーら！", category: .gameAndVariety),
    SongModel(id: "g_142", title: "Upshift", category: .gameAndVariety),
    SongModel(id: "g_143", title: "MOBILYS", category: .gameAndVariety),
    SongModel(id: "g_144", title: "ヒステリックナイトガール", category: .gameAndVariety),
    SongModel(id: "g_145", title: "Knight Rider", category: .gameAndVariety),
    SongModel(id: "g_146", title: "INTERNET OVERDOSE", category: .gameAndVariety),
    SongModel(id: "g_147", title: "Let you DIVE!", category: .gameAndVariety),
    SongModel(id: "g_148", title: "Dreadnought", category: .gameAndVariety),
    SongModel(id: "g_149", title: "Lights of Muse", category: .gameAndVariety),
    SongModel(id: "g_150", title: "Final Step!", category: .gameAndVariety),
    SongModel(id: "g_151", title: "The 90's Decision", category: .gameAndVariety),
    SongModel(id: "g_152", title: "僕の和風本当上手", category: .gameAndVariety),
    SongModel(id: "g_153", title: "Estahv", category: .gameAndVariety),
    SongModel(id: "g_154", title: "Love's Theme of BADASS ～バッド・アス 愛のテーマ～", category: .gameAndVariety),
    SongModel(id: "g_155", title: "若い力", category: .gameAndVariety),
    SongModel(id: "g_156", title: "BANG!", category: .gameAndVariety),
    SongModel(id: "g_157", title: "Define", category: .gameAndVariety),
    SongModel(id: "g_158", title: "Mjölnir", category: .gameAndVariety),
    SongModel(id: "g_159", title: "tape/stop/night", category: .gameAndVariety),
    SongModel(id: "g_160", title: "Cthugha", category: .gameAndVariety),
    SongModel(id: "g_161", title: "First Dance", category: .gameAndVariety),
    SongModel(id: "g_162", title: "enchanted love", category: .gameAndVariety),
    SongModel(id: "g_163", title: "Caterpillar Song", category: .gameAndVariety),
    SongModel(id: "g_164", title: "Reach For The Stars (Re-Colors)", category: .gameAndVariety),
    SongModel(id: "g_165", title: "BLUE ZONE", category: .gameAndVariety),
    SongModel(id: "g_166", title: "麒麟", category: .gameAndVariety),
    SongModel(id: "g_167", title: "Arty Party", category: .gameAndVariety),
    SongModel(id: "g_168", title: "田中", category: .gameAndVariety),
    SongModel(id: "g_169", title: "Luminaria", category: .gameAndVariety),
    SongModel(id: "g_170", title: "Random", category: .gameAndVariety),
    SongModel(id: "g_171", title: "ばかみたい【Taxi Driver Edition】", category: .gameAndVariety),
    SongModel(id: "g_172", title: "NightTheater", category: .gameAndVariety),
    SongModel(id: "g_173", title: "Alice's Suitcase", category: .gameAndVariety),
    SongModel(id: "g_174", title: "アイム・マイヒーロー", category: .gameAndVariety),
    SongModel(id: "g_175", title: "れっつ！みらくる☆はーどこあっ！", category: .gameAndVariety),
    SongModel(id: "g_176", title: "エナドリおいしいソング", category: .gameAndVariety),
    SongModel(id: "g_177", title: "Lost Desire", category: .gameAndVariety),
    SongModel(id: "g_178", title: "Aegleseeker", category: .gameAndVariety),
    SongModel(id: "g_179", title: "最強STRONGER", category: .gameAndVariety),
    SongModel(id: "g_180", title: "MAGENTA POTION", category: .gameAndVariety),
    SongModel(id: "g_181", title: "Vallista", category: .gameAndVariety),
    SongModel(id: "g_182", title: "コンティニュー！ feat. 藍月なくる", category: .gameAndVariety),
    SongModel(id: "g_183", title: "Sunday Night feat Kanata.N", category: .gameAndVariety),
    SongModel(id: "g_184", title: "Halfway(>∀<)", category: .gameAndVariety),
    SongModel(id: "g_185", title: "Complex Mind", category: .gameAndVariety),
    SongModel(id: "g_186", title: "DROPS feat. Such", category: .gameAndVariety),
    SongModel(id: "g_187", title: "BULK UP (GAME EXCLUSIVE EDIT)", category: .gameAndVariety),
    SongModel(id: "g_188", title: "Shooting Shower～DANCE TIME(シンディ)～", category: .gameAndVariety),
    SongModel(id: "g_189", title: "PERSONA feat. PANXI", category: .gameAndVariety),
    SongModel(id: "g_190", title: "ULTRA SYNERGY MATRIX", category: .gameAndVariety),
    SongModel(id: "g_191", title: "Play merrily NEO", category: .gameAndVariety),
    SongModel(id: "g_192", title: "OMAKENO Stroke", category: .gameAndVariety),
    SongModel(id: "g_193", title: "PUPA", category: .gameAndVariety),
    SongModel(id: "g_194", title: "アルカンシエル", category: .gameAndVariety),
    SongModel(id: "g_195", title: "Love Kills U", category: .gameAndVariety),
    SongModel(id: "g_196", title: "天使光輪", category: .gameAndVariety),
    SongModel(id: "g_197", title: "DANGEROOOOUS JUNGLE", category: .gameAndVariety),
    SongModel(id: "g_198", title: "I’m Here (feat. Merry Kirk-Holmes)", category: .gameAndVariety),
    SongModel(id: "g_199", title: "with U", category: .gameAndVariety),
    SongModel(id: "g_200", title: "神威", category: .gameAndVariety),
    SongModel(id: "g_201", title: "ozma", category: .gameAndVariety),
    SongModel(id: "g_202", title: "月面基地", category: .gameAndVariety),
    SongModel(id: "g_203", title: "Rush-Hour", category: .gameAndVariety),
])


        
        self.allSongs = songs
    }
    
    // Get songs by category
    public func songs(forCategory category: SongCategory) -> [SongModel] {
        return allSongs.filter { $0.category == category }
    }
    
    // Search songs by title
    public func searchSongs(query: String) -> [SongModel] {
        guard !query.isEmpty else { return [] }
        return allSongs.filter { $0.title.lowercased().contains(query.lowercased()) }
    }
} 